name: base
channels:
  - ibh  
  - conda-forge
dependencies:
  - pandas
  - seaborn
  - networkx
  - graphviz
  - sympy
  - cvxopt
  - numba
  - spyder
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - qgrid
  - ipysheet
